server:
  servlet:
    context-path: /fortree
spring:
  datasource:
    username: root
    password: my-secret-pw
    url: jdbc:mysql://backend.mysql:3306/fortree?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view:
    database: mysql
    database-platform: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
minio:
  url: backend.minio
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin