version: "3"

# 此脚本将拉取Docker-Hub上构建的前端后端应用镜像并启动
services:

  minio:
    image: minio/minio
    networks:
      frontend:
        aliases:
          - frontend.minio
      backend:
        aliases:
          - backend.minio
    volumes:
      - minio-data:/data
    command: [ "server", "/data" ]

  mysql:
    image: mysql:8
    networks:
      backend:
        aliases:
          - backend.mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fortree
      - MYSQL_ROOT_PASSWORD=my-secret-pw

  back_app:
    image: tank59he/fortree_back
    networks:
      frontend:
        aliases:
          - frontend.backapp
      backend:
        aliases:
          - backend.backapp
    depends_on:
      - minio
      - mysql

  front_app:
    image: tank59he/fortree_front
    networks:
      frontend:
        aliases:
          - frontend.frontapp
    ports:
      - "80:80"
    depends_on:
      - back_app
      - minio

networks:
  frontend:
  backend:

volumes:
  mysql-data:
  minio-data: